Repository Kangaroo-tine/kt-frontend, pull requests merged in 2025-10, with the labels that each got.

#44 [add] : 켈퍼 로딩화면 추가
  app/(tabs)/BottomTabs.tsx
  app/(tabs)/mainview/loading.tsx
  assets/GUI/loading.svg
  assets/GUI/loading_text.svg
Labels: UI

#46 UI/#43 알림센터 UI 구현
  app/(tabs)/BottomTabs.tsx
  app/alarmCenter.tsx
  assets/alert/bell.svg
  assets/alert/routine_active.svg
  assets/alert/routine_inactive.svg
  assets/alert/schedule_active.svg
  assets/alert/schedule_inactive.svg
  constants/Typo.ts
  package.json
  yarn.lock
Labels: UI, 👽김은혜

#48 [add] : 카카오 웹뷰 로그인 구현
  app.json
  app/(onboarding)/_layout.tsx
  app/(onboarding)/step0.tsx
  app/_layout.tsx
  app/index.tsx
  babel.config.js
  components/auth/KakaoWebViewLogin.tsx
  eas.json
  package.json
  services/auth/apiClient.ts
  services/auth/authService.ts
  services/auth/index.ts
  types/auth.ts
  types/env.d.ts
  yarn.lock
Labels: FEAT, 🦁이영주

#49 UI/#39 마이페이지 프로필 수정 UI 구현
  app/(tabs)/mainview/home.tsx
  app/(tabs)/mainview/mypage.tsx
  app/alarmCenter.tsx
  app/kelper.tsx
  app/mypages/account/manage.tsx
  app/mypages/account/withdraw.tsx
  app/mypages/notification/settings.tsx
  app/mypages/profile/edit.tsx
  assets/GUI/withdraw_account.svg
  assets/icon/blackline_icon/lock.svg
  assets/icon/blackline_icon/people.svg
  assets/icon/x_icon/red.svg
  assets/temp/temp_profile_edit.svg
  components/button/MypageEditBtn.tsx
  components/home/EmotionModal.tsx
  components/icon/bottombar/EmotionIcon.tsx
  components/shared/ReusableModal.tsx
Labels: UI, 👽김은혜
