Repository Kangaroo-tine/kt-frontend, pull requests merged in 2025-09, with the labels that each got.

#32 HOTFIX : 패키지 버전 정리
  package.json
  yarn.lock
Labels: HOTFIX

#37 [UI]메인골 추가 버튼 구현
  app/(tabs)/mainview/home.tsx
  assets/icon/plus.svg
  components/home/AddMainGoalCard.tsx
Labels: UI, 👽👓김은혜

#38 [ADD] : 목표 설정 바텀 시트 추가 및 연결
  app/(onboarding)/step1.tsx
  app/(tabs)/mainview/home.tsx
  components/Header.tsx
  components/goalstep/GoalStep1.tsx
  components/goalstep/GoalStep2.tsx
  components/goalstep/GoalStep3.tsx
  components/goalstep/GoalStep4.tsx
  components/goalstep/GoalStep5.tsx
  components/goalstep/GoalStepModal.tsx
  components/layout/OnboardingLayout.tsx
Labels: ADD, 🦁이영주
